spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dormitory_repair_system
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      static-locations: file:D:/uploads/,classpath:/static/

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.liuqiya.dormitoryrepairsystem.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

